import { columns, Payment } from "./column"
import { DataTable } from "./data-table"

async function getData(): Promise<Payment[]> {

  await new Promise((resolve) => setTimeout(resolve, 500))
  
  return [
    {
      id: "728ed52f",
      username: "john_doe",
      email: "john@example.com",
      status: "Pending",
      amount: 100,
    },
    {
      id: "489e1d42",
      username: "sarah_smith",
      email: "sarah@gmail.com",
      status: "Success",
      amount: 250,
    },
    {
      id: "573a2b91",
      username: "mike_johnson",
      email: "mike@company.com",
      status: "Processing",
      amount: 75,
    },
    {
      id: "a1b2c3d4",
      username: "emma_wilson",
      email: "emma@business.org",
      status: "Success",
      amount: 500,
    },
    {
      id: "e5f6g7h8",
      username: "alex_brown",
      email: "alex@startup.io",
      status: "Failed",
      amount: 150,
    },
    {
      id: "i9j0k1l2",
      username: "lisa_taylor",
      email: "lisa@tech.com",
      status: "Pending",
      amount: 320,
    },
    {
      id: "m3n4o5p6",
      username: "david_miller",
      email: "david@mail.com",
      status: "Success",
      amount: 89,
    },
    {
      id: "q7r8s9t0",
      username: "nina_garcia",
      email: "nina@enterprise.com",
      status: "Processing",
      amount: 1200,
    },
    {
      id: "u1v2w3x4",
      username: "tom_harris",
      email: "tom@freelance.net",
      status: "Pending",
      amount: 45,
    },
    {
      id: "y5z6a7b8",
      username: "kate_moore",
      email: "kate@agency.com",
      status: "Success",
      amount: 680,
    },
    {
      id: "c9d0e1f2",
      username: "james_clark",
      email: "james@corp.com",
      status: "Pending",
      amount: 230,
    },
    {
      id: "g3h4i5j6",
      username: "olivia_white",
      email: "olivia@design.co",
      status: "Success",
      amount: 890,
    },
    {
      id: "k7l8m9n0",
      username: "ryan_lee",
      email: "ryan@dev.io",
      status: "Failed",
      amount: 55,
    },
    {
      id: "o1p2q3r4",
      username: "sophia_martinez",
      email: "sophia@studio.com",
      status: "Processing",
      amount: 1450,
    },
    {
      id: "s5t6u7v8",
      username: "chris_anderson",
      email: "chris@web.net",
      status: "Success",
      amount: 320,
    },
    {
      id: "w9x0y1z2",
      username: "mia_thomas",
      email: "mia@digital.org",
      status: "Pending",
      amount: 175,
    },
    {
      id: "a3b4c5d6",
      username: "daniel_jackson",
      email: "daniel@media.com",
      status: "Success",
      amount: 540,
    },
    {
      id: "e7f8g9h0",
      username: "ava_hernandez",
      email: "ava@creative.io",
      status: "Failed",
      amount: 95,
    },
    {
      id: "i1j2k3l4",
      username: "ethan_king",
      email: "ethan@solutions.com",
      status: "Processing",
      amount: 780,
    },
    {
      id: "m5n6o7p8",
      username: "isabella_wright",
      email: "isabella@brand.co",
      status: "Success",
      amount: 1100,
    },
    {
      id: "q9r0s1t2",
      username: "noah_lopez",
      email: "noah@consulting.net",
      status: "Pending",
      amount: 65,
    },
    {
      id: "u3v4w5x6",
      username: "charlotte_hill",
      email: "charlotte@marketing.com",
      status: "Success",
      amount: 420,
    },
    {
      id: "y7z8a9b0",
      username: "liam_scott",
      email: "liam@finance.org",
      status: "Failed",
      amount: 200,
    },
    {
      id: "c1d2e3f4",
      username: "amelia_green",
      email: "amelia@health.io",
      status: "Processing",
      amount: 950,
    },
    {
      id: "g5h6i7j8",
      username: "mason_adams",
      email: "mason@legal.com",
      status: "Success",
      amount: 380,
    },
    {
      id: "k9l0m1n2",
      username: "harper_baker",
      email: "harper@edu.net",
      status: "Pending",
      amount: 125,
    },
    {
      id: "o3p4q5r6",
      username: "logan_nelson",
      email: "logan@travel.co",
      status: "Success",
      amount: 670,
    },
    {
      id: "s7t8u9v0",
      username: "evelyn_carter",
      email: "evelyn@food.com",
      status: "Failed",
      amount: 85,
    },
    {
      id: "w1x2y3z4",
      username: "lucas_mitchell",
      email: "lucas@retail.org",
      status: "Processing",
      amount: 1350,
    },
    {
      id: "a5b6c7d8",
      username: "aria_perez",
      email: "aria@fashion.io",
      status: "Success",
      amount: 290,
    },
    {
      id: "e9f0g1h2",
      username: "aiden_roberts",
      email: "aiden@sports.com",
      status: "Pending",
      amount: 445,
    },
    {
      id: "i3j4k5l6",
      username: "ella_turner",
      email: "ella@music.net",
      status: "Success",
      amount: 820,
    },
    {
      id: "m7n8o9p0",
      username: "jackson_phillips",
      email: "jackson@auto.co",
      status: "Failed",
      amount: 160,
    },
    {
      id: "q1r2s3t4",
      username: "scarlett_campbell",
      email: "scarlett@beauty.com",
      status: "Processing",
      amount: 530,
    },
    {
      id: "u5v6w7x8",
      username: "sebastian_parker",
      email: "sebastian@tech.org",
      status: "Success",
      amount: 1025,
    },
    {
      id: "y9z0a1b2",
      username: "grace_evans",
      email: "grace@art.io",
      status: "Pending",
      amount: 70,
    },
    {
      id: "c3d4e5f6",
      username: "mateo_edwards",
      email: "mateo@construction.com",
      status: "Success",
      amount: 485,
    },
    {
      id: "g7h8i9j0",
      username: "chloe_collins",
      email: "chloe@real-estate.net",
      status: "Failed",
      amount: 190,
    },
    {
      id: "k1l2m3n4",
      username: "henry_stewart",
      email: "henry@insurance.co",
      status: "Processing",
      amount: 750,
    },
    {
      id: "o5p6q7r8",
      username: "zoey_sanchez",
      email: "zoey@logistics.com",
      status: "Success",
      amount: 340,
    },
    {
      id: "s9t0u1v2",
      username: "owen_morris",
      email: "owen@energy.org",
      status: "Pending",
      amount: 115,
    },
    {
      id: "w3x4y5z6",
      username: "lily_rogers",
      email: "lily@pharma.io",
      status: "Success",
      amount: 925,
    },
    {
      id: "a7b8c9d0",
      username: "jack_reed",
      email: "jack@telecom.com",
      status: "Failed",
      amount: 60,
    },
    {
      id: "e1f2g3h4",
      username: "penelope_cook",
      email: "penelope@hospitality.net",
      status: "Processing",
      amount: 1180,
    },
    {
      id: "i5j6k7l8",
      username: "leo_morgan",
      email: "leo@agriculture.co",
      status: "Success",
      amount: 275,
    },
    {
      id: "m9n0o1p2",
      username: "layla_bell",
      email: "layla@entertainment.com",
      status: "Pending",
      amount: 395,
    },
    {
      id: "q3r4s5t6",
      username: "benjamin_murphy",
      email: "benjamin@security.org",
      status: "Success",
      amount: 610,
    },
    {
      id: "u7v8w9x0",
      username: "riley_bailey",
      email: "riley@aerospace.io",
      status: "Failed",
      amount: 140,
    },
    {
      id: "y1z2a3b4",
      username: "ellie_rivera",
      email: "ellie@biotech.com",
      status: "Processing",
      amount: 865,
    },
    {
      id: "c5d6e7f8",
      username: "william_cooper",
      email: "william@manufacturing.net",
      status: "Success",
      amount: 1500,
    },
    {
      id: "g9h0i1j2",
      username: "nora_richardson",
      email: "nora@education.co",
      status: "Pending",
      amount: 205,
    },
    {
      id: "k3l4m5n6",
      username: "luke_cox",
      email: "luke@gaming.com",
      status: "Success",
      amount: 730,
    },
    {
      id: "o7p8q9r0",
      username: "hazel_howard",
      email: "hazel@nonprofit.org",
      status: "Failed",
      amount: 50,
    },
    {
      id: "s1t2u3v4",
      username: "gabriel_ward",
      email: "gabriel@research.io",
      status: "Processing",
      amount: 990,
    },
  ]
}

export default async function DemoPage() {
  const data = await getData()

  return (
    <div className="container mx-auto py-10">
      <DataTable columns={columns} data={data} />
    </div>
  )
}
