import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/AppSidebar";
import { ThemeProvider } from "@/components/Provider/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
            <SidebarProvider defaultOpen={defaultOpen}>
          <Sidebar />
          <main className="flex-1 w-full">
            <Navbar />
            <div className="px-4">{children}</div>
          </main>
          </SidebarProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
